import json
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

import yaml
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from integrations import create_confluence_page, create_jira_issue, import_xray_test_execution
from rag_redis import build_redis_vectorstore, get_retriever

ROOT = Path(__file__).resolve().parents[1]
AGENT_INDEX = ROOT / ".github" / "agents" / "agent-index.yaml"
SKILL_INDEX = ROOT / ".github" / "skills" / "skill-index.yaml"
SKILL_DIR = ROOT / ".github" / "skills"
OUT_DIR = ROOT / "langchain-implementation" / "runs"


@dataclass
class AgentDef:
    agent_id: str
    display_name: str
    purpose: str
    primary_skills: List[str]


def load_yaml(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_skill_text(skill_map: Dict[str, Dict[str, str]], skill_id: str) -> str:
    skill_file = skill_map.get(skill_id, {}).get("file")
    if not skill_file:
        return f"[Skill {skill_id} not found in skill index]"
    skill_path = SKILL_DIR / skill_file
    if not skill_path.exists():
        return f"[Skill file missing: {skill_file}]"
    return skill_path.read_text(encoding="utf-8")


def build_agent_defs() -> List[AgentDef]:
    agent_data = load_yaml(AGENT_INDEX)
    return [
        AgentDef(
            agent_id=a["id"],
            display_name=a["display_name"],
            purpose=a["purpose"],
            primary_skills=a.get("primary_skills", []),
        )
        for a in agent_data.get("agents", [])
    ]


def build_skill_map() -> Dict[str, Dict[str, str]]:
    skill_data = load_yaml(SKILL_INDEX)
    return {s["id"]: s for s in skill_data.get("skills", [])}


def run_sequential_pipeline(
    user_goal: str,
    model_name: str = "gpt-4o-mini",
    use_rag: bool = True,
) -> Dict[str, Any]:
    llm = ChatOpenAI(model=model_name, temperature=0)
    parser = StrOutputParser()
    agents = build_agent_defs()
    skill_map = build_skill_map()
    retriever = None

    if use_rag:
        if os.getenv("RAG_REINDEX", "false").lower() == "true":
            build_redis_vectorstore()
        retriever = get_retriever()

    state: Dict[str, Any] = {
        "user_goal": user_goal,
        "current_artifacts": [],
        "history": [],
    }

    for agent in agents:
        compiled_skills = []
        for skill_id in agent.primary_skills:
            skill_text = load_skill_text(skill_map, skill_id)
            compiled_skills.append(f"## Skill: {skill_id}\n{skill_text}")

        skill_context = "\n\n".join(compiled_skills)
        rag_context = ""
        if retriever is not None:
            docs = retriever.invoke(f"{agent.display_name} guidance for goal: {user_goal}")
            rag_context = "\n\n".join([d.page_content for d in docs])
            if not rag_context:
                rag_context = "[No RAG context returned]"

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are {display_name}. Purpose: {purpose}\n"
                    "You are part of a sequential multi-agent software delivery pipeline.\n"
                    "Produce concise, actionable output and include:\n"
                    "1) decisions\n2) artifacts produced\n3) handoff instructions for next agent.",
                ),
                (
                    "human",
                    "User goal:\n{user_goal}\n\n"
                    "Current pipeline state:\n{state_json}\n\n"
                    "RAG context from Redis vector store:\n{rag_context}\n\n"
                    "Relevant skills:\n{skill_context}\n\n"
                    "Respond in markdown with sections: Decisions, Artifacts, Handoff.",
                ),
            ]
        )

        chain = prompt | llm | parser
        agent_output = chain.invoke(
            {
                "display_name": agent.display_name,
                "purpose": agent.purpose,
                "user_goal": state["user_goal"],
                "state_json": json.dumps(state, indent=2),
                "rag_context": rag_context,
                "skill_context": skill_context,
            }
        )

        state["history"].append(
            {
                "agent_id": agent.agent_id,
                "display_name": agent.display_name,
                "output": agent_output,
            }
        )
        state["current_artifacts"].append(
            {
                "from_agent": agent.agent_id,
                "summary": f"Output generated by {agent.display_name}",
            }
        )

    return state


def publish_to_management_tools(result: Dict[str, Any]) -> Dict[str, Any]:
    summary = f"BMAD Sequential Run: {result['user_goal'][:120]}"
    full_text = json.dumps(result, indent=2)
    jira_result = create_jira_issue(
        summary=summary,
        description="Automated update from LangChain pipeline run.\n\n" + full_text[:25000],
    )
    confluence_result = create_confluence_page(
        title=f"BMAD Run - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        content_markdown=full_text[:50000],
    )

    xray_payload = {
        "testExecutionKey": os.getenv("XRAY_TEST_EXECUTION_KEY", "AUTO-GENERATED"),
        "info": {"summary": "BMAD automated test lifecycle run"},
        "tests": [
            {
                "testKey": os.getenv("XRAY_TEST_KEY", "AUTO-T1"),
                "status": "PASSED",
                "comment": "Placeholder status from sequential pipeline scaffold",
            }
        ],
    }
    xray_result = import_xray_test_execution(xray_payload)
    return {
        "jira": jira_result,
        "confluence": confluence_result,
        "xray": xray_result,
    }


def write_run_outputs(result: Dict[str, Any]) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_dir = OUT_DIR / f"run-{ts}"
    run_dir.mkdir(parents=True, exist_ok=True)

    json_path = run_dir / "result.json"
    json_path.write_text(json.dumps(result, indent=2), encoding="utf-8")

    md_lines = ["# Sequential Agent Run", "", f"Goal: {result['user_goal']}", ""]
    for item in result["history"]:
        md_lines.append(f"## {item['display_name']} (`{item['agent_id']}`)")
        md_lines.append(item["output"])
        md_lines.append("")

    (run_dir / "result.md").write_text("\n".join(md_lines), encoding="utf-8")
    return run_dir


if __name__ == "__main__":
    goal = os.getenv(
        "PIPELINE_GOAL",
        "Create complete testing lifecycle from user story to gherkin, selenium, defects, security, and maintenance.",
    )
    model = os.getenv("PIPELINE_MODEL", "gpt-4o-mini")
    use_rag = os.getenv("PIPELINE_USE_RAG", "true").lower() == "true"
    publish_mgmt = os.getenv("PIPELINE_PUBLISH_MGMT", "false").lower() == "true"

    result = run_sequential_pipeline(user_goal=goal, model_name=model, use_rag=use_rag)
    if publish_mgmt:
        result["management_publish"] = publish_to_management_tools(result)
    output_dir = write_run_outputs(result)
    print(f"Sequential run complete. Outputs written to: {output_dir}")
